[workspace]
resolver = "2"
members = [
	"engine",
	"model",
	"pdn",
	"ui"
]

[profile.dev]
opt-level = 3

[profile.release]
lto = "fat"
panic = 'abort'
incremental = false
codegen-units = 1
strip = "symbols"
