[package]
name = "ai"
version = "0.1.0"
authors = ["botahamec"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
model = {path = "../model"}

[dev-dependencies]
criterion = "0.3"